with Ada.Text_IO;
with Test_Core_Foundation;
with Test_Types;
with Test_Errors;
with Test_Result;
with Test_Config;
with Test_Version;
with Test_Task_Handle;
with Test_Scheduler_Basic;
with Test_Runtime_Builder;
with Test_Runtime_Lifecycle;
with Test_Spawn_Tasks;
with Test_Fault_Isolation;
with Test_Scheduler_Fairness;
with Test_Shutdown;
with Test_Runtime_Stress;
with Test_Future_Basic;
with Test_Promise_Completion;
with Test_Future_Failure;
with Test_Future_Cancellation;
with Test_Awaitable;
with Test_Block_On;
with Test_Future_Chaining;
with Test_Future_Stress;
with Test_Sleep;
with Test_Timeout;
with Test_Interval;
with Test_Deadline;
with Test_Timer_Cancel;
with Test_Fake_Clock;
with Test_Timer_Accuracy;
with Test_Timer_Stress;
with Test_Readiness;
with Test_IO_Token;
with Test_Platform_Backend;
with Test_Reactor_Lifecycle;
with Test_Reactor_Registration;
with Test_Reactor_Wakeup;
with Test_Reactor_Shutdown;
with Test_Reactor_Many_Resources;
with Test_Runtime_Reactor_Integration;
with Test_TCP_Listener;
with Test_TCP_Connect;
with Test_TCP_Echo;
with Test_TCP_Concurrent_Clients;
with Test_TCP_Timeout;
with Test_TCP_Shutdown;
with Test_UDP_Socket;
with Test_Net_Errors;
with Test_Async_Mutex;
with Test_Async_Semaphore;
with Test_Async_Event;
with Test_Async_Condvar;
with Test_Async_Barrier;
with Test_Async_RWLock;
with Test_Once_Cell;
with Test_Sync_Cancellation;
with Test_Sync_Stress;
with Test_Bounded_Channel;
with Test_Unbounded_Channel;
with Test_Oneshot_Channel;
with Test_Broadcast_Channel;
with Test_Watch_Channel;
with Test_Channel_Backpressure;
with Test_Stream;
with Test_Actor_Mailbox;
with Test_Select;
with Test_Channel_Stress;
with Test_Cancel_Token;
with Test_Cancel_Source;
with Test_Task_Group;
with Test_Join_Set;
with Test_Scope;
with Test_Supervisor_Restart;
with Test_Supervisor_Failure_Policy;
with Test_Deadline_Propagation;
with Test_Runtime_Structured_Shutdown;
with Test_Cancellation_Stress;
with Test_Metrics;
with Test_Tracing;
with Test_Diagnostics;
with Test_Test_Support;
with Test_Fake_Runtime;
with Test_Release_Integrity;

procedure Test_Runner is
begin
   Ada.Text_IO.Put_Line ("Aion Module 1 through Module 10 test runner");

   Test_Core_Foundation;
   Test_Types;
   Test_Errors;
   Test_Result;
   Test_Config;
   Test_Version;

   Test_Task_Handle;
   Test_Scheduler_Basic;
   Test_Runtime_Builder;
   Test_Runtime_Lifecycle;
   Test_Spawn_Tasks;
   Test_Fault_Isolation;
   Test_Scheduler_Fairness;
   Test_Shutdown;
   Test_Runtime_Stress;

   Test_Future_Basic;
   Test_Promise_Completion;
   Test_Future_Failure;
   Test_Future_Cancellation;
   Test_Awaitable;
   Test_Block_On;
   Test_Future_Chaining;
   Test_Future_Stress;

   Test_Sleep;
   Test_Timeout;
   Test_Interval;
   Test_Deadline;
   Test_Timer_Cancel;
   Test_Fake_Clock;
   Test_Timer_Accuracy;
   Test_Timer_Stress;

   Test_Readiness;
   Test_IO_Token;
   Test_Platform_Backend;
   Test_Reactor_Lifecycle;
   Test_Reactor_Registration;
   Test_Reactor_Wakeup;
   Test_Reactor_Shutdown;
   Test_Reactor_Many_Resources;
   Test_Runtime_Reactor_Integration;

   Test_TCP_Listener;
   Test_TCP_Connect;
   Test_TCP_Echo;
   Test_TCP_Concurrent_Clients;
   Test_TCP_Timeout;
   Test_TCP_Shutdown;
   Test_UDP_Socket;
   Test_Net_Errors;

   Test_Async_Mutex;
   Test_Async_Semaphore;
   Test_Async_Event;
   Test_Async_Condvar;
   Test_Async_Barrier;
   Test_Async_RWLock;
   Test_Once_Cell;
   Test_Sync_Cancellation;
   Test_Sync_Stress;

   Test_Bounded_Channel;
   Test_Unbounded_Channel;
   Test_Oneshot_Channel;
   Test_Broadcast_Channel;
   Test_Watch_Channel;
   Test_Channel_Backpressure;
   Test_Stream;
   Test_Actor_Mailbox;
   Test_Select;
   Test_Channel_Stress;

   Test_Cancel_Token;
   Test_Cancel_Source;
   Test_Task_Group;
   Test_Join_Set;
   Test_Scope;
   Test_Supervisor_Restart;
   Test_Supervisor_Failure_Policy;
   Test_Deadline_Propagation;
   Test_Runtime_Structured_Shutdown;
   Test_Cancellation_Stress;

   Test_Metrics;
   Test_Tracing;
   Test_Diagnostics;
   Test_Test_Support;
   Test_Fake_Runtime;
   Test_Release_Integrity;

   Ada.Text_IO.New_Line;
   Ada.Text_IO.Put_Line ("All Aion Module 1 through Module 10 tests passed.");
end Test_Runner;
